/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java3Lab4;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.FocusEvent;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class bai11 extends javax.swing.JFrame {

    public bai11() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu6 = new javax.swing.JMenu();
        popBold = new javax.swing.JCheckBoxMenuItem();
        popItalic = new javax.swing.JCheckBoxMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        popred = new javax.swing.JRadioButtonMenuItem();
        popblue = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        txtHello = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edPage = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnNew = new javax.swing.JMenuItem();
        mnOpen = new javax.swing.JMenuItem();
        mnSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnRead = new javax.swing.JMenuItem();
        mnGreen = new javax.swing.JMenuItem();
        mnBlue = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnTextColer = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jScrollPane1.setViewportView(jTree1);

        jMenu6.setText("font");

        popBold.setSelected(true);
        popBold.setText("bold");
        popBold.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                popBoldItemStateChanged(evt);
            }
        });
        jMenu6.add(popBold);

        popItalic.setSelected(true);
        popItalic.setText("italic");
        jMenu6.add(popItalic);

        jPopupMenu1.add(jMenu6);
        jPopupMenu1.add(jSeparator6);

        jMenu7.setText("Color");

        buttonGroup1.add(popred);
        popred.setSelected(true);
        popred.setText("red");
        popred.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                popredItemStateChanged(evt);
            }
        });
        jMenu7.add(popred);

        buttonGroup1.add(popblue);
        popblue.setText("blue");
        jMenu7.add(popblue);

        jPopupMenu1.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-file-48.png")); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnUser.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-user-40.png")); // NOI18N
        btnUser.setFocusable(false);
        btnUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUser);

        jSeparator5.setBackground(new java.awt.Color(255, 0, 51));
        jToolBar1.add(jSeparator5);

        btnExit.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-power-button-48.png")); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        txtHello.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHello.setText("hello");

        jScrollPane2.setViewportView(edPage);

        jMenu1.setText("File");

        mnNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnNew.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-add-24.png")); // NOI18N
        mnNew.setText("New");
        mnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNewActionPerformed(evt);
            }
        });
        jMenu1.add(mnNew);

        mnOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpen.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-open-file.gif")); // NOI18N
        mnOpen.setText("Open");
        mnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpenActionPerformed(evt);
            }
        });
        jMenu1.add(mnOpen);

        mnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnSave.setIcon(new javax.swing.ImageIcon("D:\\hoc\\java3\\src\\java3Lab4\\img\\icons8-save-24.png")); // NOI18N
        mnSave.setText("Save");
        mnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveActionPerformed(evt);
            }
        });
        jMenu1.add(mnSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Coler");

        mnRead.setText("Read");
        mnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReadActionPerformed(evt);
            }
        });
        jMenu2.add(mnRead);

        mnGreen.setText("Green");
        mnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGreenActionPerformed(evt);
            }
        });
        jMenu2.add(mnGreen);

        mnBlue.setText("Blue");
        mnBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBlueActionPerformed(evt);
            }
        });
        jMenu2.add(mnBlue);
        jMenu2.add(jSeparator2);

        mnTextColer.setText("text coler");
        mnTextColer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTextColerActionPerformed(evt);
            }
        });
        jMenu2.add(mnTextColer);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("System");

        mnAbout.setText("About us");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu5.add(mnAbout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu5.add(mnExit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtHello))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtHello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNewActionPerformed
        // TODO add your handling code here:
        edPage.setText("");
    }//GEN-LAST:event_mnNewActionPerformed

    private void mnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGreenActionPerformed
        // TODO add your handling code here:
        txtHello.setBackground(Color.green);
    }//GEN-LAST:event_mnGreenActionPerformed

    private void mnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReadActionPerformed
        // TODO add your handling code here:
        txtHello.setBackground(Color.red);
    }//GEN-LAST:event_mnReadActionPerformed

    private void mnBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBlueActionPerformed
        // TODO add your handling code here:
        txtHello.setBackground(Color.blue);
    }//GEN-LAST:event_mnBlueActionPerformed

    private void mnTextColerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTextColerActionPerformed
        // TODO add your handling code here:
        Color c= JColorChooser.showDialog(this, "choce color", Color.WHITE);
        txtHello.setBackground(c);
        //txtHello.setForeground(c);
    }//GEN-LAST:event_mnTextColerActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        String str = "Program menu";
        str += "\n Author: chienpx";
        str += "\n Last update: 04-07-2023";
        str += "\n Education: fpoly";
        JOptionPane.showMessageDialog(null,str, "gioi thieu",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        String str = "Program menu";
        str += "\n Author: chienpx";
        str += "\n Last update: 04-07-2023";
        str += "\n Education: fpoly";
        JOptionPane.showMessageDialog(null,str, "gioi thieu",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void mnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooes = new JFileChooser();
        int result = fchooes.showOpenDialog(null);
        if (result== JFileChooser.APPROVE_OPTION) {
            try {
                edPage.setPage("file:///"+fchooes.getSelectedFile().getPath());
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_mnOpenActionPerformed

    private void mnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveActionPerformed
        // TODO add your handling code here:
        JFileChooser fChooser= new JFileChooser();
        int result = fChooser.showSaveDialog(null);
        if (result== JFileChooser.APPROVE_OPTION) {
            File fname = fChooser.getSelectedFile();
            try {
                PrintWriter pw =new PrintWriter(fname);
                pw.println(edPage.getText());
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_mnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        edPage.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        jPopupMenu1.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseReleased

    private void popBoldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_popBoldItemStateChanged
        // TODO add your handling code here:
        changeStyle();
    }//GEN-LAST:event_popBoldItemStateChanged
public void changeStyle(){
        if (popBold.isSelected() && popItalic.isSelected()) {
            txtHello.setFont(new Font("arial",Font.BOLD|Font.ITALIC,24));
        }else if (popBold.isSelected()) {
            txtHello.setFont(new Font("arial",Font.BOLD,24));
        }
        else if (popItalic.isSelected()) {
            txtHello.setFont(new Font("arial",Font.ITALIC,24));
        }else {
            txtHello.setFont(new Font("arial",Font.PLAIN,24));
        }
    }
    private void popredItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_popredItemStateChanged
        // TODO add your handling code here:
        changeColor();
    }//GEN-LAST:event_popredItemStateChanged
    public void changeColor(){
        if (popred.isSelected()) {
            edPage.setBackground(Color.red);
        }
        if (popblue.isSelected()) {
            edPage.setBackground(Color.blue);
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane edPage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnBlue;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnGreen;
    private javax.swing.JMenuItem mnNew;
    private javax.swing.JMenuItem mnOpen;
    private javax.swing.JMenuItem mnRead;
    private javax.swing.JMenuItem mnSave;
    private javax.swing.JMenuItem mnTextColer;
    private javax.swing.JCheckBoxMenuItem popBold;
    private javax.swing.JCheckBoxMenuItem popItalic;
    private javax.swing.JRadioButtonMenuItem popblue;
    private javax.swing.JRadioButtonMenuItem popred;
    private javax.swing.JTextField txtHello;
    // End of variables declaration//GEN-END:variables
}
