
import java.util.*;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Bai2 extends javax.swing.JFrame {

    private String header[] = {"RegID", "Name", "Standard"};
    private DefaultTableModel model = new DefaultTableModel(header, 0);
    ArrayList<Student> list = new ArrayList<>();
    String url = "jdbc:sqlserver://localhost:1433;database=KidszoneSchool;user=sa;password =123";
    int index = -1;
    
    PreparedStatement pstInsert = null;
    PreparedStatement pstDelete = null;
    PreparedStatement pstUpdate = null;
    
    String sqlInsert = "Insert into Students (name,Address,ParentName,Phone,standard) values(?,?,?,?,?)";
    String sqlDelete = "Delete from Students where RegID = ?";
    String sqlUpdate = "Update Students set name = ?, Address=?, ParentName=?,Phone=? ,standard=? where regID=?";
    ResultSet rs;

    public Bai2() {
        initComponents();
        setLocationRelativeTo(null);
        loadCombobox();
        loadData();
        btnUpdate.setEnabled(false);
    }

    private void loadCombobox() {
        DefaultComboBoxModel modelcbo1 = new DefaultComboBoxModel();
        DefaultComboBoxModel modelcbo2 = new DefaultComboBoxModel();
        String sql1 = "select * from Standars";
        try {
            Connection con = DriverManager.getConnection(url);
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql1);
            while (rs.next()) {
                modelcbo1.addElement(rs.getString(1));
                modelcbo2.addElement(rs.getFloat(3));
//                cbb_Stan.addItem(rs.getString(1));
//                cbb_Fees.addItem(rs.getString(3));
            }
            cbb_Stan.setModel(modelcbo1);
            cbb_Fees.setModel(modelcbo2);
        } catch (Exception e) {
            System.out.println("" + e);

        }
    }

    private void loadData() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            String sql = "select * from students";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            model.setRowCount(0);
            list.clear();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1),
                    rs.getString(2),
                    rs.getString(6)});
                Student sv = new Student(rs.getInt(1),
                        rs.getString(2),
                        rs.getString(3),
                        rs.getString(4),
                        rs.getString(5),
                        rs.getString(6),
                        rs.getDate(7));
                list.add(sv);
            }
            tblStudent.setModel(model);
            System.out.println("" + list.size());
            // đóng các đối tượng để đảm bảo tài nguyên
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Loi: " + e);
        }
    }

    boolean validates() {
        if (txt_Name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name ko dc trong ", "Chu y", 1);
            txt_Name.requestFocus();
            return false;
        }
        if (txt_Address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address khong duoc de trong ", "Chu y", 1);
            txt_Address.requestFocus();
            return false;
        }
        if (txt_PName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ParentsName khong duoc de trong ", "Chu y", 1);
            txt_PName.requestFocus();
            return false;
        }

        if (txt_Con.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Contact(Phone) khong duoc de trong va phai la 7-12 so ", "Chu y", 1);
            txt_Con.requestFocus();
            return false;
        }
        if ((cbb_Stan.getSelectedIndex() == 0)) {
            JOptionPane.showMessageDialog(this, cbb_Stan.getSelectedItem());
        }
        return true;
    }

    private void clearForm() {
        txt_Name.setText("");
        txt_Address.setText("");
        txt_PName.setText("");
        txt_Con.setText("");
        cbb_Stan.setSelectedIndex(0);
        cbb_Fees.setSelectedIndex(0);
        txt_Name.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Address = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt_PName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Con = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbb_Stan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbb_Fees = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPre = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(0).setMinWidth(50);
            tblStudent.getColumnModel().getColumn(0).setMaxWidth(50);
            tblStudent.getColumnModel().getColumn(2).setMinWidth(200);
            tblStudent.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        jLabel1.setText("Name:");

        jLabel2.setText("Address:");

        txt_Address.setColumns(20);
        txt_Address.setLineWrap(true);
        txt_Address.setRows(5);
        jScrollPane2.setViewportView(txt_Address);

        jLabel3.setText("ParentName:");

        jLabel4.setText("ContactNo:");

        jLabel5.setText("Standad:");

        cbb_Stan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web1", "Web2", "Mob", "UDPM", "DEL1", "DEL2", "Java" }));
        cbb_Stan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_StanActionPerformed(evt);
            }
        });

        jLabel6.setText("Fees:");

        cbb_Fees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_FeesActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        btnCancel.setText("New");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext);

        btnPre.setText("Pre...");
        btnPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreActionPerformed(evt);
            }
        });
        jPanel1.add(btnPre);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(txt_PName)
                            .addComponent(txt_Con)
                            .addComponent(txt_Name)
                            .addComponent(cbb_Stan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_Fees, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbb_Stan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbb_Fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearForm();
        txt_Name.setEnabled(true);
        txt_Address.setEnabled(true);
        txt_PName.setEnabled(true);
        txt_Con.setEnabled(true);
        cbb_Fees.setEnabled(true);
        cbb_Stan.setEnabled(true);
        txt_Name.requestFocus();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void cbb_StanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_StanActionPerformed
        cbb_Fees.setSelectedIndex(cbb_Stan.getSelectedIndex());
    }//GEN-LAST:event_cbb_StanActionPerformed

    private void cbb_FeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_FeesActionPerformed
        cbb_Stan.setSelectedIndex(cbb_Fees.getSelectedIndex());
    }//GEN-LAST:event_cbb_FeesActionPerformed
    private void hienThiSinhVienlenForm(int index) {
        int regID = (Integer) tblStudent.getValueAt(index, 0);
        String standard = (String) tblStudent.getValueAt(index, 2);
        if (index == -1) {
            return;
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);

            String sql1 = "select * from students where RegID = ? and standard = ?";
            PreparedStatement statement1 = con.prepareStatement(sql1);
            statement1.setInt(1, regID);
            statement1.setString(2, standard);
            ResultSet rsStudent = statement1.executeQuery();

            while (rsStudent.next()) {
                txt_Name.setText(String.valueOf(rsStudent.getString(2)));
                txt_Address.setText(rsStudent.getString(3));
                txt_PName.setText(rsStudent.getString(4));
                txt_Con.setText(rsStudent.getString(5));
                cbb_Stan.setSelectedItem(rsStudent.getString(6));
            }

            String sql2 = "select * from standars where standardID = ?";
            PreparedStatement statement2 = con.prepareStatement(sql2);
            statement2.setString(1, standard);
            ResultSet rsStandard = statement2.executeQuery();

            while (rsStandard.next()) {
                cbb_Fees.setSelectedItem(rsStandard.getFloat("fees"));
            }
        } catch (Exception e) {
            System.out.println("Loi: " + e);
        }

    }
    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        int index = tblStudent.getSelectedRow();
        hienThiSinhVienlenForm(index);
        txt_Name.setEnabled(false);
        txt_Address.setEnabled(false);
        txt_PName.setEnabled(false);
        txt_Con.setEnabled(false);
        cbb_Stan.setEnabled(false);
        cbb_Fees.setEnabled(false);
    }//GEN-LAST:event_tblStudentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int index = tblStudent.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng trước khi sửa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int n;
            //update
            //set cac tham so
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            pstUpdate = con.prepareStatement(sqlUpdate);
            int i = Integer.parseInt(tblStudent.getValueAt(index, 0).toString());
            pstUpdate.setString(1, this.txt_Name.getText().trim());
            pstUpdate.setString(2, this.txt_Address.getText().trim());
            pstUpdate.setString(3, this.txt_PName.getText().trim());
            pstUpdate.setString(4, this.txt_Con.getText().trim());
            pstUpdate.setString(5, (String) cbb_Stan.getSelectedItem());
            pstUpdate.setInt(6, i);
            n = pstUpdate.executeUpdate();//thuc thi
            if (n > 0) {
                this.loadData();
            }
            pstUpdate.close();
            con.close();
        } catch (Exception e) {
            System.out.println("" + e);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        btnUpdate.setEnabled(true);
        btnCancel.setEnabled(true);
        btnEdit.setEnabled(true);
        txt_Name.setEnabled(true);
        txt_Address.setEnabled(true);
        txt_PName.setEnabled(true);
        txt_Con.setEnabled(true);
        cbb_Stan.setEnabled(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreActionPerformed
        index--;
        if (index < 0) {
            index = list.size() - 1;
        }
        tblStudent.setRowSelectionInterval(index, index);
        hienThiSinhVienlenForm(index);
    }//GEN-LAST:event_btnPreActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        index++;
        if (index > list.size() - 1) {
            index = 0;
        }
        tblStudent.setRowSelectionInterval(index, index);
        hienThiSinhVienlenForm(index);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = tblStudent.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng trước khi xóa!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            int i = Integer.parseInt(tblStudent.getValueAt(index, 0).toString());
            int n;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            pstDelete = con.prepareStatement(sqlDelete);
            pstDelete.setInt(1, i);
            n = pstDelete.executeUpdate();
            if (n > 0) {
                this.loadData();
                this.clearForm();
            }
            pstDelete.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Loi: " + e);
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (!validates()) {
            return;
        }
        String name = txt_Name.getText().trim();
        String addr = txt_Address.getText().trim();
        String parentName = txt_PName.getText().trim();
        String phone = txt_Con.getText().trim();
        String standard = (String) cbb_Stan.getSelectedItem();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(url);
            pstInsert = con.prepareStatement(sqlInsert);
            pstInsert.setString(1, name);
            pstInsert.setString(2, addr);
            pstInsert.setString(3, parentName);
            pstInsert.setString(4, phone);
            pstInsert.setString(5, standard);
            int addRows = pstInsert.executeUpdate();
            if (addRows > 0) {
                this.loadData();
                clearForm();
                JOptionPane.showMessageDialog(this, "Students Details Have Been Save", "Successfull", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to save data in database", "Error",
                    JOptionPane.ERROR_MESSAGE);
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbb_Fees;
    private javax.swing.JComboBox<String> cbb_Stan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextArea txt_Address;
    private javax.swing.JTextField txt_Con;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_PName;
    // End of variables declaration//GEN-END:variables
}
